#!/bin/sh

tt=$1
tr=$2
hosts=$tt $tr
intf=eth1

curl -LO https://github.com/richardcochran/linuxptp/raw/refs/tags/v4.2/configs/gPTP.cfg
for host in $hosts; do
    scp -O gPTP.cfg $host:
done

for host in $hosts; do
    ssh $host tcpdump -i $intf -w $host.pcap &
done

ssh $tt ptp4l -f gPTP.cfg -i $intf --twoStepFlag 0 --BMCA noop --serverOnly 1 --priority1 0 --priority2 0 &
ssh $tr ptp4l -f gPTP.cfg -i $intf --twoStepFlag 0 --BMCA noop --clientOnly 1 --step_threshold 1 &

sleep 10

jobs -p | xargs kill

for host in $hosts; do
    scp -O $host:$host.pcap .
done
