#!/bin/sh

tt=$1
tr=$2
hosts="$tt $tr"
intf=eth1

set -x

curl -LO https://github.com/richardcochran/linuxptp/raw/refs/tags/v4.2/configs/gPTP.cfg --silent
for host in $hosts; do
    scp -q -O gPTP.cfg $host:
done

for host in $hosts; do
    ssh $host tcpdump -i $intf -w $host.pcap &
done

ssh $tt ptp4l -f gPTP.cfg -i $intf --twoStepFlag 0 --BMCA noop --serverOnly 1 --priority1 0 --priority2 0 &
ssh $tr ptp4l -f gPTP.cfg -i $intf --twoStepFlag 0 --BMCA noop --clientOnly 1 --step_threshold 1 &

sleep 10

for host in $hosts; do
    ssh $host killall ptp4l
    ssh $host killall tcpdump
done

for host in $hosts; do
    scp -q -O $host:$host.pcap .
done
