#!/bin/sh

tx=$1
rx=$2
hosts="$tx $rx"
user=root
intf=eth1

scp -q -O tx $user@$tx:

for host in $hosts; do
    ssh $user@$host killall tcpdump >/dev/null 2>&1
done

ssh $user@$tx tcpdump -i $intf -t -c1 -xx ether proto 0x88f7 2>/dev/null >txpkt &
txpid=$!
ssh $user@$rx tcpdump -i $intf -t -c1 -xx ether proto 0x88f7 2>/dev/null >rxpkt &
rxpid=$!

sleep 1

ssh $user@$tx /root/tx

wait $txpid
wait $rxpid

echo txpkt
cat txpkt

echo rxpkt
cat rxpkt

# Pad tx packet so we don't get a diff due to padding
sed -i -r "$ s/^.*$/& 0000/" txpkt
if diff -U5 txpkt rxpkt; then
    echo "FAILED: Packets match => packet was not timestamped"
else
    echo "PASSED: Packets differ => packet was timestamped"
fi

