#!/bin/bash

tx=$1
rx=$2
hosts="$tx $rx"
user=root
intf=eth1

for host in $hosts; do
    ssh $user@$host killall tcpdump >/dev/null 2>&1
    ssh $user@$host killall onestep >/dev/null 2>&1
    scp -q -O onestep $user@$host:
done

# ssh $user@$tx tcpdump -i $intf -t -c1 -xx ether proto 0x88f7 2>/dev/null >txpkt &
# txpid=$!
# ssh $user@$rx tcpdump -i $intf -t -c1 -xx ether proto 0x88f7 2>/dev/null >rxpkt &
# rxpid=$!

sleep 1

ssh $user@$rx /root/onestep rx eth1 >rx &
sleep 1
ssh $user@$tx /root/onestep tx eth1 >tx

# wait $txpid
# wait $rxpid

echo "Transmitted"
cat tx | sed -E 's/^\s+//g' | tr '\n' ' '
echo
echo

echo "Received"
cat rx | sed -E 's/^\s+//g' | tr '\n' ' '
echo
echo

echo "Diff"
diff -U0 --label tx --label rx tx <(grep -v rx_timestamp rx) > diff
cat diff
echo

if \
    test 10 = $(cat diff | wc -l) \
    && grep "\-    correctionField: 0" diff >/dev/null \
    && grep "\-    secs: 0" diff >/dev/null \
    && grep "\-    nsecs: 0" diff >/dev/null \
; then
    echo "PASSED: Packet was timestamped"
else
    echo "FAILED: Packets was not timestamped"
fi
