#!/bin/bash

tx=$1
rx=$2
hosts="$tx $rx"
user=root
intf=eth1

for host in $hosts; do
    ssh $user@$host killall tcpdump >/dev/null 2>&1
    ssh $user@$host killall onestep >/dev/null 2>&1
done

scp -qO target/aarch64-unknown-linux-gnu/debug/onestep $user@$tx:

ssh $user@$tx tcpdump -i $intf -t -c1 -xx ether proto 0x88f7 >txpkt 2>/dev/null &
txpid=$!
ssh $user@$rx tcpdump -i $intf -t -c1 -xx ether proto 0x88f7 >rxpkt 2>/dev/null &
rxpid=$!

sleep 1

ssh $user@$tx ./onestep

wait $txpid
wait $rxpid

echo txpkt
cat txpkt

echo rxpkt
cat rxpkt
