#!/bin/sh

tt=$1
tr=$2
hosts="$tt $tr"
user=root
intf=eth1

set -x

curl -LO https://github.com/richardcochran/linuxptp/raw/refs/tags/v4.2/configs/gPTP.cfg --silent
for host in $hosts; do
    scp -q -O gPTP.cfg $user@$host:
done

for host in $hosts; do
    ssh $user@$host tcpdump -i $intf -w $host.pcap &
done

sleep 1

ssh $user@$tt strace /root/ptp4l -f gPTP.cfg -i $intf --twoStepFlag 0 --BMCA noop --serverOnly 1 --priority1 0 --priority2 0 >ptp4l-strace.log 2>&1 &
ssh $user@$tr ptp4l -f gPTP.cfg -i $intf --twoStepFlag 0 --BMCA noop --clientOnly 1 --step_threshold 1 &

sleep 5

for host in $hosts; do
    ssh $user@$host killall ptp4l
    ssh $user@$host killall tcpdump
done

for host in $hosts; do
    scp -q -O $user@$host:$host.pcap .
done
